### ISSUE TITLE
Replace deprecated GAPlugin Analytics

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#189]
Our current implementation use [angulartics](https://angulartics.github.io/) (Web analytics for AngularJS applications) with [gaPlugin](https://github.com/phonegap-build/GAPlugin) to use native SDK. Angulartics provide 2 plugins for Google Analytics: angulartics.google.analytics and angulartics.google.analytics.cordova for hybrid App.
gaPlugin is not maintained and is [incompatible with OneSignal](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/59)

One alternative is [cordova-plugin-google-analytics](https://www.npmjs.com/package/cordova-plugin-google-analytics) although the [author seems to not maintain anymore](https://github.com/danwilson/google-analytics-plugin/issues/228)

The best solution should be to continue using angulartics (should refactor our current implementation) but replace gaPlugin on [angulartics.google.analytics.cordova ](https://github.com/angulartics/angulartics/blob/master/src/angulartics-ga-cordova.js) by cordova-plugin-google-analytics. [angulartics plugin is looking for maintainers](https://github.com/angulartics/angulartics/issues/390)

```js
angular.module('sample', ['angulartics', 'angulartics.google.analytics.cordova'])
	.config(function ($routeProvider, $analyticsProvider) {
...
})
```

and on templates:

```html
<button analytics-on analytics-event="Button 2" analytics-category="Commands" class="btn btn-primary">Button 2</button>
```

Below tutorials about danwilson/google-analytics-plugin:

- https://www.thepolyglotdeveloper.com/2014/06/using-google-analytics-ionicframework/
- http://www.phonegaptutorial.com/integrate-google-analytics-into-your-phonegap-app/
- http://phonegappro.com/tutorials/integrate-google-analytics-with-phonegap-application/

By default angulartics track location.url, see `src/angulartics/angulartics.js`. We need to overwrite it to track page title.

```js
  var url = $analytics.settings.pageTracking.basePath + $location.url();
      $analytics.pageTrack(url);
```

**Comment by elbidone** [comment]
An alternative solution seems to be [angulartics](https://angulartics.github.io/) with module `angulartics.google.analytics.cordova`

```js
angular.module('sample', ['angulartics', 'angulartics.google.analytics.cordova'])
	.config(function ($routeProvider, $analyticsProvider) {
...
})
```

and 

```html
<button analytics-on analytics-event="Button 2" analytics-category="Commands" class="btn btn-primary">Button 2</button>
```

**Comment by elbidone** [comment]
another alternative: https://github.com/appfeel/analytics-google

**Comment by elbidone** [comment]
angulartics required gaPlugin: http://stackoverflow.com/questions/28867485/integrating-angulartics-with-ionic-framework

**Comment by elbidone** [comment]
Use [ngCordova](http://ngcordova.com/docs/plugins/googleAnalytics/) to load module ['ngCordova.plugins.googleAnalytics'](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/googleAnalytics.js)

**Comment by belgacea** [comment]
Wait for [this](https://groups.google.com/forum/#!topic/firebase-talk/MKfIzAtNNuA)
