### ISSUE TITLE
google-analytics-plugin upgrade, replace window.analytics by window.ga

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#219]
v1.0.0 -- [api change](https://github.com/danwilson/google-analytics-plugin#release-note) from window.analytics to window.ga, 'analytics' is deprecated since 1.0.0

See meumobi/ng-meumobi-utils#9

**Comment by danconte72** [comment]
- must to update do most recent ng-meumobi-utils

**Comment by danconte72** [comment]
https://github.com/meumobi/IRmobi/commit/00b4782a3b11238bb0429ad64fbd502bd664c342
