### ISSUE TITLE
Replace the pagination for a infinite scroll

### ISSUE THREAD

**Issue by t4deu** [meumobi/IRmobi#22]
Or at least for a "load more" button, at the bottom of the list

**Comment by elbidone** [comment]
https://sroze.github.io/ngInfiniteScroll/demo_basic.html

**Comment by elbidone** [comment]
|name | github | status |
|--- | ---- | ---- |
|infinite-scroll|https://github.com/infinite-scroll/infinite-scroll | no more maintened |
|ng-infinite-scroll| https://github.com/ash-developer/ng-infinite-scroll| only 1 contributor, last commit 2 years agor|
|angular-infinite-scroll|https://github.com/zxcabs/angular-infinite-scroll.git|2 contributors, last commit 3 years ago|
|angular-sn-infinite-scroll | https://github.com/thisissoon/sn-infinite-scroll.git| only 1 contributor|
|angular-infinite-scroll-xs | https://github.com/agustik/angular-scroll | only 1 contributor|
|ng-infinite-scroller-origin|https://github.com/sroze/ngInfiniteScroll| 26 contributors|
