### ISSUE TITLE
event is displayed as past when occurs today

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#234]

**Comment by danconte72** [comment]
I couldn't reproduce the bug
![image](https://user-images.githubusercontent.com/32454870/39885262-85fc18e2-5462-11e8-83ae-c41534fb18e6.png)

**Comment by danconte72** [comment]
- should reproduce data copying from clients

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/40013139-13425fea-5783-11e8-816f-4dfa6d6bf2b2.png)

**Comment by elbidone** [comment]
Close if we can't reproduce

**Comment by elbidone** [comment]
label of issue is wrong, should be "event is displayed as past when occurs **today**" (I edit the title)
Today event should be considered as future.

**Comment by danconte72** [comment]
update isFutureDate on src/js/app/components/calendar.js

**Comment by danconte72** [comment]
we should check if event is in future
passing event.end_date despiste event.start_date
> return isFutureDate(e.start_date);

**Comment by danconte72** [comment]
created a today event
![image](https://user-images.githubusercontent.com/32454870/70567242-50901e80-1b74-11ea-81ba-57fb860e0818.png)
before fix, it has not listed
![image](https://user-images.githubusercontent.com/32454870/70567160-29395180-1b74-11ea-921e-6fb908fcfb88.png)

after it is listed as future event 
![image](https://user-images.githubusercontent.com/32454870/70567293-6ef61a00-1b74-11ea-8c45-fc60b48039b9.png)
