### ISSUE TITLE
lot of null as page name on analytics

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#242]
![overview_-_analytics](https://cloud.githubusercontent.com/assets/9011612/23176283/2c26b4d6-f841-11e6-8778-c0df892ca319.png)

**Comment by elbidone** [comment]
If I download the App and open a category, the name of category is null, maybe it's the reason of this bug

**Comment by danconte72** [comment]
- Null happens on open an app before choosing a category; 
- If you chose a category the screen is correctly set, also when go back to home;
