### ISSUE TITLE
updates for ios11 and iPhone X

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#253]
https://webkit.org/blog/7929/designing-websites-for-iphone-x
http://blog.ionic.io/ios-11-checklist/

**Comment by danconte72** [comment]
follow the tutorials

**Comment by danconte72** [comment]
[How to](https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493) update to iPhone X

**Comment by danconte72** [comment]
should to review xml file, splash screens
