### ISSUE TITLE
Improve UX of events to order items from older to newer and open page on most recent open event

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#259]
inspired by iOS Calendar

**Comment by danconte72** [comment]
- Update view, to show from older events to newer;
- Te most recent event must be focused on open view;
- Set a visual signal for past events, like a gray icon, or a line to indicate past, or highlight the most recent

**Comment by danconte72** [comment]
I have tested the API, and today it only responds correctly the limit, on DESC order

**Comment by elbidone** [comment]
so what's the recommendatio

**Comment by danconte72** [comment]
Keep the api in the same way, and reverse array response on app

**Comment by danconte72** [comment]
- I've correctly set the next event and added a marker to 'call for scroll';
- To now I put an anchor to click an go to next;
- Next step is set this behavior when the screen is loaded;

**Comment by danconte72** [comment]
The scroll is scrolling to the right event but not opening the correctly

**Comment by danconte72** [comment]
To open/colapse the right event we must to change the rule, from `$index == 0` to `item.next` [here](https://github.com/meumobi/IRmobi/blob/030a5f74b55aa1bdfd086fe374a4be63439b45a9/src/templates/events/list.html#L24)
