### ISSUE TITLE
Move API requests to https

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#260]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- update PROJECTS/[project]/environments/production.json 
  apiUrl field

**Comment by danconte72** [comment]
should update cdnUrl too?

**Comment by elbidone** [comment]
yes, we should move all requests to https
