### ISSUE TITLE
Monitor Stock quotes RI 

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#267]
Monitor Stock quotes RI => Scalyr
- [EMBR3](http://stocks.mobi.comunique-se.com.br/?action=googlify&codes=EMBR3)
- [RADL3](http://stocks.mobi.comunique-se.com.br/?action=googlify&codes=RADL3)
- [MGLU3](http://stocks.mobi.comunique-se.com.br/?action=googlify&codes=MGLU3)
- [ITUB4](http://stocks.mobi.comunique-se.com.br/?action=googlify&codes=ITUB4)
- [ESTC3](http://stocks.mobi.comunique-se.com.br/?action=googlify&codes=ESTC3)

Should check a valid result is returned

**Comment by danconte72** [comment]
https://eu.scalyr.com/events?filter=(tag%3D%27httpMonitor%27)%20%24url%3D%22https%3A%2F%2Fstocks.mobi.comunique-se.com.br%22&teamToken=LxiLJcjvN4TQeugi6eciKw-- we are monitoring stocks
