### ISSUE TITLE
update Launch Screens to follow new config.xml conventions

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#268]
I've recently updated config.xml to apply Ionic conventions on splash assets names.
Should update resources of triunfo, magazineluiza, biosev, embraer, raiadrogasil, santander projects

To generate assets should use `ionic cordova resources -f` command, see [official doc](https://ionicframework.com/docs/cli/cordova/resources/) for more details.

**Comment by danconte72** [comment]
where can I find the original images to crop?

**Comment by elbidone** [comment]
on repository PROJECTS/.../res/screen/... select the larger image

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/44462178-1ea72180-a5ea-11e8-92f0-7ec020216d68.png)
 I will try later
