### ISSUE TITLE
Generate screenshots iOS 

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#280]
Use following devices/sizes to be resized on iOS Media Manager
- iPad Pro (2nd Generation) 12.9-inch Display
- 5.5-inch Display

Check [RADL3](https://itunes.apple.com/pt/app/radl3/id1045677511?mt=8) and [MGL](https://itunes.apple.com/br/app/magazineluiza-ri/id1135963989?mt=8) examples.

Should do screenshots of:
- home
- share
- events
- contact form
- audio stream

**Comment by elbidone** [comment]
save on gdrive [PROJECT]/Screenshots/{iPad, ios, android}/{en,pt}
Should do screenshots for each supported language

**Comment by danconte72** [comment]
### pt
- [x] iPhone 
- [ ] iPad
- [ ] Android 
### en
- [x] iPhone
- [ ] iPad
- [ ] Android

**Comment by elbidone** [comment]
[Screenshots specs](https://help.apple.com/app-store-connect/#/devd274dd925)
iPad should be 2732 x 2048 px

**Comment by danconte72** [comment]
I've updated the files.
To take larger screenshots in Simulator, on menu uncheck the option Debug > Optimize Rendering for Window Scale.
