### ISSUE TITLE
Add privacy policy for iOS

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#291]
### Expected behaviour
https://developer.apple.com/news/?id=08312018a

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
This policy covers which informations we get and how we use them. Keep in mind that IRmobi is a solution to improve Investors Relationship. None personal information is required and/or saved. For technical purpose we only save your device specification anonymously. We will not sell or redistribute it to anyone. We take your privacy seriously and will take all measures to protect such information.

**Comment by elbidone** [comment]
https://www.santander.com.br/institucional-santander/seguranca/politica-de-privacidade

**Comment by danconte72** [comment]
Privacy [Policy](https://docs.google.com/document/u/1/d/e/2PACX-1vTpJaQ3RT9iFAIDT-THz8r0_JV1qwQUBzMun-2pFoc9kYhho3U62SzeDWVbQOeruvtThZk3wYGcTeIF/pub)

**Comment by vdias38** [comment]
[Construindo a Política de Privacidade de Seu Aplicativo Android](https://www.thiengo.com.br/construindo-a-politica-de-privacidade-de-seu-aplicativo-android-agora-obrigatorio)

- [supervia: termo de uso e politica de privacidade](https://www.supervia.com.br/pt-br/termo-de-uso-e-politica-de-privacidade-aplicativo-supervia)
- [seuApp: politica de privacidade](https://seuapp.com/privacidade/)
- twitter: politica de privacidade [pt](https://twitter.com/pt/privacy), [en](https://twitter.com/en/privacy)
- [constructApp](https://constructapp.io/pt/politica-de-privacidade/)
- [hoost: politica de privacidade](https://www.hoost.com.br/politica-de-privacidade-para-os-aplicativos-android-e-ios/)
- [band: termo de uso e politica de privacidade](https://www.band.uol.com.br/segundatela/politicas.html)

**Comment by danconte72** [comment]
our privace policy is up to date in all ios apps
