### ISSUE TITLE
logo on header is "blurred" seems to be downsized

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#3]

**Comment by t4deu** [comment]
The logo image must have a width of 123px and a maximum height of 40px to prevent aliasing and quality loss

**Comment by elbidone** [comment]
Cielo logo follows these requirements but clients continue considering it as blurred.
We should investigate more.
I've setted an icon for Cielo App with ratio 123:41 but size 585x196px
I've also altered css adding following conf, but it should be improved, should apply a padding on whole header (50px -5px padding-top) and limit logo to 40px height
```
.navbar-brand {
  padding: 5px 0 0 10px;
}
```
On iOs it looks good but not on android, should test with a lower sized image, for example 246x80px

**Comment by elbidone** [comment]
We solved it since we've updated size of header logo to 246 x 80px
