### ISSUE TITLE
WARNING ITMS-90704: Missing App Store Icon

### ISSUE THREAD

**Issue by danconte72** [meumobi/IRmobi#302]
### Expected behaviour
Tell us what should happen
WARNING ITMS-90704:
 "Missing App Store Icon. iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via App Store Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ for more information."

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
[Official Cordova doc](https://cordova.apache.org/docs/en/latest/config_ref/images.html)

[Adobe forum thread](https://forums.adobe.com/thread/2437351) about this topic recommend to use a 1024x1024px default icon, in order to do it we should update the the `copy-icon` task of `gulpfile.js`:

```
// Copy Default APP icon on root
gulp.task('copy-icon', function () {
	return gulp.src('./res/icon/ios/iTunesArtwork@2x.png', {
		cwd: cwd
	})
	.pipe($.rename('icon.png'))
	.pipe(gulp.dest(config.dest))
});
```
