### ISSUE TITLE
Imgs from It. feeds are broken

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#308]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Some of them appears, but the majority not.
![screenshot_2018-11-07-20-17-05](https://user-images.githubusercontent.com/9011612/48158395-50b35000-e2ca-11e8-9d82-dc719b4ae76f.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
domain of thumbs is wrong. Should update `config/environment/comunique-se.php`

Config::write('Sites.domain', 'itau.mobi.comunique-se.com.br');

=> **should create an itau.comunique-se env**

**Comment by elbidone** [comment]
I've done the fix of sites.domain directly on server and re-processed all pt feeds:
for each category
1. disable extension to reset checksum
2. "delete all items"
3. enable extension

**Comment by danconte72** [comment]
I've  re-processed  all en feeds;

**Comment by elbidone** [comment]
The issue is not only due domain, issue remains after updating domain.
The protocol is wrong http vs https, and the img-cache not follow 301. Should update protocol to https for all imgs.

**Comment by elbidone** [comment]
on itau.c-se env, I've updated `sitebuilder/app/models/meu_mobi.php`, it used `http://` instead of `https://` 

```
...
  public static function url($path, $full = false)
  {
    return $full ? '**https:/**/'.self::domain().$path : $path;
  }
...

Strange because on github the [code](https://github.com/meumobi/sitebuilder/commit/80cf357c3337c8df4abc2cbae2ec53cc7727a8de#diff-f7b9f0a603b6c117039758862c88fca0) is ok.

**Comment by danconte72** [comment]
It.c-se last commit is https://github.com/meumobi/sitebuilder/commit/cd5aafc88aab4d9cff10220d2ab4547683ff03ef

The changes on ```sitebuilder/app/models/meu_mobi.php``` 
was commited after on https://github.com/meumobi/sitebuilder/commit/80cf357c3337c8df4abc2cbae2ec53cc7727a8de

Checking the diff between the most recent commit and the last released on it.c-se 
`$ git diff ece0b19 80cf357 > my.patch`
There is no main changes for investors, mostly for infomobi.

**Comment by danconte72** [comment]
Check on mong which items have thumbs with http protocol
```js
$ db.items.find({"medias.thumbnails.url":{$regex : "http://.*"}})
```

**Comment by danconte72** [comment]
It nether c-se are redirecting images
![image](https://user-images.githubusercontent.com/32454870/48847509-dfbf6e00-ed88-11e8-97f1-b7206c72e85b.png)
![image](https://user-images.githubusercontent.com/32454870/48847519-eb129980-ed88-11e8-8781-d8f9c5bfbdbd.png)

**Comment by danconte72** [comment]
Actually there is no redirect on it.c-se
[http://itau.mobi.comunique-se.com.br/api/itauri.mobi.comunique-se.com.br/categories/629/items?limit=15&order=published,DESC&page=1](http://itau.mobi.comunique-se.com.br/api/itauri.mobi.comunique-se.com.br/categories/629/items?limit=15&order=published,DESC&page=1)

**Comment by elbidone** [comment]
and if you enable it, should it work?

**Comment by danconte72** [comment]
Urls will be update on meumobi/sitebuilder#622
