### ISSUE TITLE
use app icon for push instead of sent by REST POST to onesignal API

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#310]
### Actual behaviour
we should upload icon for android push on meumobi config.
But it raises an overload on server when push is launched.

**Comment by danconte72** [comment]
Add push icon on Android app (phonegap build scenario)
1. Add large icon on [project](https://documentation.onesignal.com/docs/customize-notification-icons#section-2-create-project-paths)
   ```<project-root>/platforms/android/app/src/main/res/drawable-xxxhdpi/ic_onesignal_large_icon_default.png```
2. Uncomment this tag https://github.com/meumobi/IRmobi/blob/6e9214ca8a0b2e9795ac9122dfe6118b2052933b/src/config.xml#L107
3. Don't send large_icon reference on api call 

Large icon must to be 256x256

**Comment by danconte72** [comment]
Test
- build an bv apk with this news configs, adding a image for example
![image](https://user-images.githubusercontent.com/32454870/48909854-79545180-ee55-11e8-8baa-6785dbef01e6.png)

- when I sent a push for tests devices without passing large_icon url
![image](https://user-images.githubusercontent.com/32454870/48909777-49a54980-ee55-11e8-92e3-20c8d2606d15.png)
- when I sent a push for tests devices passing large_icon [url](http://www.biosev.com/wp-content/themes/biosev/images/logo-biosev.png)
![image](https://user-images.githubusercontent.com/32454870/48909811-63469100-ee55-11e8-8fc9-53b8ad794831.png)
- I disabled bv on onesignal again

**Comment by danconte72** [comment]
Add this files for all projects
