### ISSUE TITLE
file open error on Android 8.x

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#311]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Observed by a client on `Android 8.0.0; SM-G950F` open file not work. No more details about...

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
could be related to following [issue](https://github.com/pwlin/cordova-plugin-file-opener2/issues/225) from [cordova-plugin-file-opener2](https://github.com/pwlin/cordova-plugin-file-opener2)

**Comment by elbidone** [comment]
Check #313 for more details

**Comment by elbidone** [comment]
fixed with upgrade of `cordova-plugin-fileopener2` on v2.4.0

**Comment by klochko7** [comment]
**elbidone**, good day !  Help please ! How can I download v2.4.0 ? I have an issue with exposed beyond app through intent.getdata() on Android 8.

**Comment by klochko7** [comment]
**elbidone**, I am using 2.0.19 version downloaded from github. Where can I find plugin 2.1.0 ?
