### ISSUE TITLE
Important changes to your Google Analytics for mobile apps properties

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#312]
> in October 2019 we will begin to sunset our Google Analytics for mobile apps reporting and the Google Analytics Services SDK. We are investing our resources in the latest style of app reporting in Google Analytics that works in conjunction with Firebase – Google's integrated app developer platform. 

[Get started with Google Analytics app reporting](https://support.google.com/firebase/answer/6317479)

**Comment by danconte72** [comment]
As we did for est and it whom still working
create a GA Web property and create an App view

**Comment by danconte72** [comment]
OR migrate to firebase Analytics 
[Google Analytics for Firebase migration guide](https://storage.googleapis.com/support-kms-prod/QZuv6pLepAgDzg8G7PVZ1hWDgBd28t7I5GWF)

**Comment by vdias38** [comment]
We are using an [outdated branch](https://github.com/hettiger/google-analytics-plugin.git#no-idfa) due to [idfa issue](https://github.com/danwilson/google-analytics-plugin/issues/218#issuecomment-248194925)

### Cordova hook to solve idfa issue
A solution to continue using [danwilson plugin](https://github.com/danwilson/google-analytics-plugin) is to use [Cordova hooks to remove "AdSupport.framework" and "libAdIdAccess" references from the plugin.xml](https://github.com/danwilson/google-analytics-plugin/issues/218#issuecomment-349078091)

> I think attaching it to after_build would be more appropriate.
Also, just to be safe, it can be added to
<platform name="ios">
section of config.xml file

### Integration of ga.js without cordova plugin
ELSE we can [move to vanilla script solution as some people recommend](https://github.com/danwilson/google-analytics-plugin/issues/550#issuecomment-531561630).

**Comment by danconte72** [comment]
| Property         | Est   | Maga  | It    |
|------------------|-------|-------|-------|
| ios version      | 2.5.5 | 2.5.2 | 2.5.4 |
| android version  | 2.5.4 | 2.5.2 | 2.5.4 |
| GA property tyep | web   | app   | web   |
| Working          | yes   | no    | no    |

**Comment by danconte72** [comment]
We can use a solution similar we did on [How to track Ionic 4 PWA and Native page views and events on Google Analytics](http://meumobi.github.io/ionic/pwa/2018/04/12/using-analytics-ionic-app-pwa-native.html)

**Comment by danconte72** [comment]
On ng-meumobi-utils we have a vanilla ga as fallback https://github.com/meumobi/ng-meumobi-utils/blob/1ed0e5441f1c4f9e405227cd27215476f33e27d3/src/lib/Cordova/Analytics.js#L122

**Comment by danconte72** [comment]
'This property received hits from the Google Analytics Services SDK, which we have begun sunsetting'

**Comment by danconte72** [comment]
I've updated app to use vanilla ga.
Created a web view for some tracker-ids
Got hits on realtime, but will wait until they processed on GA

**Comment by danconte72** [comment]
I've created a web view for it and biosev
Sent some hits yesterday.
Only Biosev had this hits processed.

**Comment by danconte72** [comment]
## Why it happens
- GA Client properties had received hits from obsolete Google Analytics Services SDK;
- This properties stopped to process their data, even tough we can get this on realtime;
- Affected properties will be deleted by google;

## How to fix
- Update apps to not use Google Analytics Services SDK and use vanilla GA;
- Create new GA properties (web) for each client;

## How to test
1. Build an app with the a New GA property
2. Use app and monitor it on Realtime 
3. Wait until the next day to check if data were correctly processed

**Comment by danconte72** [comment]
- Google Analytics upgraded https://github.com/meumobi/IRmobi/commit/13c5c261d01c648dd05359efddb511a738bd90a5

**Comment by danconte72** [comment]
Hits from yesterday were correctly processed by GA
![image](https://user-images.githubusercontent.com/32454870/70713916-d7a0dc00-1cc5-11ea-80a3-1af659e6e29b.png)
