### ISSUE TITLE
Remove phone call plugin

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#315]
On Android 8.0.0 sytem launch a confirm dialog when app start

![test_estacio_ir_app_on_android_8_0_0_with_genymotion_-_victor_dias_meumobi_com_-_meumobi_mail](https://user-images.githubusercontent.com/9011612/48835683-b565b480-ed78-11e8-96e4-fd35692b0c6c.png)

**Comment by danconte72** [comment]
I've been faced the same in 6.0
![image](https://user-images.githubusercontent.com/32454870/49011581-f8030480-f15d-11e8-
9801-2bbf1649a965.png)

**Comment by elbidone** [comment]
Remove the original:

`cordova plugin remove cordova-plugin-uniquedeviceid`
Install the updated version:

`cordova plugin add cordova-unique-device-id`

see Paldom/UniqueDeviceID#27 for more details

**Comment by elbidone** [comment]
Should check if id generated by both plugins is same.
Check request made by app to save device

**Comment by danconte72** [comment]
Id with previous plugin
```"uuid":"58986b98-df3c-c189-0000-000000000008"```
Id with new plugin
```"uuid":"00000000-0000-0000-5898-6b98df3cc189"```
There is no more permission request... the numbers are almost the same but with different order

**Comment by danconte72** [comment]
There is some problems with the plugin… 
- It use some deprecated functions
https://developer.android.com/reference/android/telephony/TelephonyManager#getDeviceId() 
- This function Requires Permission: READ_PHONE_STATE or that the calling app has carrier privileges (see hasCarrierPrivileges()). 
https://developer.android.com/reference/android/telephony/TelephonyManager.html#getSimSerialNumber()

**Comment by danconte72** [comment]
How to get devices modified after Date
```$db.devices.find({     "modified" : {$gt: ISODate("2018-10-01")} }).count()```

**Comment by danconte72** [comment]
We've decided to migrate to the new plugin, even uuid becoming different.

**Comment by elbidone** [comment]
> if you want absolutely identify a particular device physically, you can try to **use the ANDROID_ID** solution. 

Source: [How to retrieve an Unique ID to identify Android devices ?](https://medium.com/@ssaurel/how-to-retrieve-an-unique-id-to-identify-android-devices-6f99fd5369eb)

The `cordova-plugin-uniquedeviceid` use a combination of ANDROID_ID, `TelephonyManager.getDeviceId()` and `TelephonyManager.getSimSerialNumber)`. 
- DeviceId is changed if apk signing certificate is changed, device is reset or different Android User Account is used
- SimSerialNumber is changed if SIM is changed

Then we could reasonably consider DeviceId and SimSerialnumber are useless
