### ISSUE TITLE
none page view tracked on itau App

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#320]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
- check if only occurs w/ itau
- check since which date it occurs (on itau and/or others)

**Comment by danconte72** [comment]
there is no **pageviews**
on 
**itau** 
![image](https://user-images.githubusercontent.com/32454870/54710285-18e4d080-4b26-11e9-9376-be841e8294cf.png)
**estacio** 
![image](https://user-images.githubusercontent.com/32454870/54710224-f5218a80-4b25-11e9-9d97-9b913752665b.png)
but are **events**
**itau**
![image](https://user-images.githubusercontent.com/32454870/54710309-25692900-4b26-11e9-9100-462a3d49596a.png)
**estacio**
![image](https://user-images.githubusercontent.com/32454870/54710271-11252c00-4b26-11e9-8240-6d6b2111a4e7.png)
but on **magalu**
are **events**
![image](https://user-images.githubusercontent.com/32454870/54710348-3dd94380-4b26-11e9-8cd1-855fa35c870c.png)
and **screenviews**
![image](https://user-images.githubusercontent.com/32454870/54710375-4b8ec900-4b26-11e9-8751-b81ddc04c4a7.png)

**Comment by danconte72** [comment]
- magalu has screenviews
- it and estacio have pageviews

- it and estacio ga id were created as website 
![image](https://user-images.githubusercontent.com/32454870/54711111-f2279980-4b27-11e9-8987-571ba06bb171.png)
- while magalu as mobile app
![image](https://user-images.githubusercontent.com/32454870/54711150-09668700-4b28-11e9-87d2-581c44e29db4.png)

- mobile app demands a firebase project 
![image](https://user-images.githubusercontent.com/32454870/54710819-467e4980-4b27-11e9-927d-4da3c4221f59.png)

**Comment by danconte72** [comment]
IrMobi use google-analytics-plugin to track views 
and it demands mobile app 
https://github.com/danwilson/google-analytics-plugin/issues/274#issuecomment-238574519 


- But there is a way to get app and web site data with the same [analytics tracker](https://developers.google.com/analytics/devguides/collection/analyticsjs/screens#using_filters_for_app-only_or_web-only_views)

**Comment by danconte72** [comment]
- Create an [app View](https://support.google.com/analytics/answer/1009714) on itau
- Use app and check if screenviews are tracked
- Check if history is available on this new view

**Comment by danconte72** [comment]
- App view correct track screenviews in realtime
![image](https://user-images.githubusercontent.com/32454870/54712280-a88c7e00-4b2a-11e9-8025-63a9877f5b27.png)
- events are available on app view too
![image](https://user-images.githubusercontent.com/32454870/54712465-1f297b80-4b2b-11e9-88bb-71e53d0106fa.png)
- App view correct track screenviews in realtime on estacio too
![image](https://user-images.githubusercontent.com/32454870/54712418-f99c7200-4b2a-11e9-83c8-1810768ce9a5.png)
- events are available on app view too
![image](https://user-images.githubusercontent.com/32454870/54712447-0f119c00-4b2b-11e9-96fb-5c1792cafb15.png)

- no screen views on history
![image](https://user-images.githubusercontent.com/32454870/54712563-5d269f80-4b2b-11e9-88cb-70d0e1735555.png)

- should check tomorrow if today's screen views will be show on be available

**Comment by vdias38** [comment]
# Why it happens
- Before Itau, all apps have created as mobile App
- Google request to migrate to firebase for App Analytics, then we've applied a workaround to continue using Google Analytics: create GA account as website.
- google-analytics-plugin send screenViews (mobileApp behavior) but default GA view created on dashboard display pagesViews (website behavior)
- Events, users, location, etc. are ok
- the issues concerns Itau and Estacio

# How to fix it
- Create an App view on GA to display ScreenViews
- It only tracks screenView after creation of App View, previously views are lost.

Then we should keep website views for history from app launch until today. And later when useless remove them.

The target solution should be to migrate to [Google Analytics for Firebase](https://firebase.google.com/docs/analytics/).
