### ISSUE TITLE
results loads on headlines failed randomly

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#325]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Randomly observed results on headlines are not loaded

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've faced 2017 loads correctly before 2018 empty loads

**Comment by danconte72** [comment]
On load I logged latestYear and got 2017 before 2018.
![image](https://user-images.githubusercontent.com/32454870/56585065-7780ec80-65b3-11e9-8af5-54392421859c.png)
2017 is coming from the first request, when app loads contents from all sidemenu categories.

**Comment by danconte72** [comment]
headlines years filter was getting wrong years because missformatted slice
```js
//from
 if (vm.headlines) {
vm.years = vm.years.slice(vm.years.length-4, 4);
//to
 if (vm.headlines) {
vm.years = vm.years.slice(vm.years.length-4);
```
