### ISSUE TITLE
App can't handle application/mp3 files

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#327]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![Screenshot_2019-04-23-11-29-30](https://user-images.githubusercontent.com/9011612/56575724-6ab5c600-65be-11e9-9833-efd287931149.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
The source mime-type `application/mp3` doesn't exist. If we check on [mime-db](https://github.com/jshttp/mime-db) audios with mp3 extension should use `audio/mpeg` mime-type, it's what we declare on `ng-meumobi-utils/src/lib/Files.js``
I don't understand why service process_remote_media doesn't fix it, so please:

1. check what is returned on RSS fo this specific media
2. how it is handled by process_remote_media service, means from file which data this service extract
3. what is returned by meumobi

**Comment by vdias38** [comment]
On [results feed](https://www.itau.com.br/relacoes-com-investidores/FeedMeuMobi.aspx?idCanal=lyyjtVJ4BExsF2fi1Kfy0Q==) the media type is correct `audio/mpeg`
```xml
<media:content url="https://www.itau.com.br/relacoes-com-investidores/Download.aspx?Arquivo=ob87/LkrUi6FmIuXg526ng==" fileSize="12004352" type="audio/mpeg" medium="audio">
<media:title>itauunibanco4t18port20190205_4937034</media:title>
</media:content>
```

**Comment by danconte72** [comment]
I've logged how this types are got.
They are coming from content-type
```LOG
[2019-04-23 19:04:24] sitebuilder.INFO: gettin type {"url":"https://www.itau.com.br/relacoes-com-investidores/Download.aspx?Arquivo=BK/UeLe2os3My/KF5JyVDA==","type":"application/mp3","origin":"content-type","component":"remote_media.generic_media_handler"} []
[2019-04-23 19:04:24] sitebuilder.INFO: remote media info downloaded {"item_id":"5cbf5e5c10f0ed20138b4583","url":"https://www.itau.com.br/relacoes-com-investidores/Download.aspx?Arquivo=BK/UeLe2os3My/KF5JyVDA==","info":{"type":"application/mp3","extension":null,"length":14555504},"processing_time":0.81551098823547,"component":"remote_media"} []
```
![image](https://user-images.githubusercontent.com/32454870/56609825-6ef4da00-65e4-11e9-9de7-7277aa75cb51.png)


On [estacio](https://ri.estacio.br/FeedMeuMobi.aspx?idCanal=QueRek9lx6lY8glbPTs6XA==) audio/mpeg content-types are correct .
Ex: http://ri.estacio.br/Download.aspx?Arquivo=0T2DfBNiT1hmg2mTY9XPXg==
![image](https://user-images.githubusercontent.com/32454870/56610366-a617bb00-65e5-11e9-97a4-a5ec15541b43.png)

Must to be `application/octet-stream`

**Comment by vdias38** [comment]
ok, but why process remote media service don't fix it? the purpose of this
service is to prevent wrong mime types.

Em Ter, 23 de abr de 2019 20:34, Daniel Antonio Conte <
notifications@github.com> escreveu:

**Comment by danconte72** [comment]
I didn't understand why it only get filename if content-type is application/octet-stream
https://github.com/meumobi/sitebuilder/blame/master/sitebuilder/lib/meumobi/sitebuilder/services/ProcessRemoteMedia/GenericMediaHandler.php#L69 

If we remove these check it will get the file extension and based on extension set the correctly mime type

**Comment by danconte72** [comment]
- I've checked sitebuilder history and the oldest reference, that I found, for octet-stream is this [commit](https://github.com/meumobi/sitebuilder/commit/f21ffdde7028972f107a21f456e489d355642e40#diff-c7410827f67ea1f213770f8a8103d13d)
- [application/octet-stream](url) 
> ... is the default for binary files. As it means unknown binary file, browsers usually don't execute it, or even ask if it should be executed. They treat it as if the Content-Disposition header was set to attachment, and propose a "Save As" dialog.
- for our purpose we can only check the prefix application 
> [application](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#Types) - Any kind of binary data that doesn't fall explicitly into one of the other types; either data that will be executed or interpreted in some way or binary data that requires a specific application or category of application to use. Generic binary data (or binary data whose true type is unknown) is application/octet-stream. Other common examples include application/pdf, application/pkcs8, and application/zip.

So a fix can be update Content-type check on sitebuilder
- from: if == application/octet-stream
- to if starts with application/ 

PS:  although application/mp3 is not a valid [Media-type](https://www.iana.org/assignments/media-types/media-types.xhtml#application)

**Comment by danconte72** [comment]
update on [sitebuilder](https://github.com/meumobi/sitebuilder/blame/master/sitebuilder/lib/meumobi/sitebuilder/services/ProcessRemoteMedia/GenericMediaHandler.php#L69)   
```php
//FROM
if ($type == 'application/octet-stream' && $response->headers('Content-Disposition')) {
//TO
if (($type == 'application/octet-stream' || $type == 'application/pdf' )  && $response->headers('Content-Disposition')) {
```

it will solved on https://github.com/meumobi/sitebuilder/issues/656
