### ISSUE TITLE
update menu icons on itau css

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#331]
Below selected icons from [font-awesome 4.7](https://fontawesome.com/v4.7.0/icons/)

- Agenda: fa-calendar
- investcast: fa-podcast
- Vídeos: fa-video-camera 

Should update for en and pt sites

**Comment by danconte72** [comment]
### unicode
Agenda: fa-calendar - f073
investcast: fa-podcast - f2ce
Vídeos: fa-video-camera - f03d

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/56685432-58b05200-66a8-11e9-97c8-81a636964b80.png)
