### ISSUE TITLE
error msg "couldn't handle UTI" when open .xlsx media on iOS

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#338]
### Expected behaviour
Tell us what should happen

### Actual behaviour
When download following item.media on iOS from ["Pilar 3 e Índice de Importância Sistêmica e Global" feed
](https://www.itau.com.br/relacoes-com-investidores/FeedMeuMobi.aspx?idCanal=oPS8xa6hj3/WDYSEUcUnxw==) raises "Could not handle UTI" error (toast msg)

```xml
<item>
<title>Anexo I e II - Pilar 3 - 1T19</title>
<media:content url="https://www.itau.com.br/relacoes-com-investidores/Download.aspx?Arquivo=iiok2i4kY6cYUEQyCTLyaA==" fileSize="894976" type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" medium="document">
<media:title>Anexos I e II - Pilar 3 - 1T19</media:title>
</media:content>
<guid isPermaLink="false">
https://www.itau.com.br/relacoes-com-investidores/Show.aspx?idMateria=tpt+wxl7z0oYKVyP2pGWUg==
</guid>
<link>
https://www.itau.com.br/relacoes-com-investidores/Show.aspx?idMateria=tpt+wxl7z0oYKVyP2pGWUg==
</link>
<pubDate>Thu, 02 May 2019 14:43:00 GMT</pubDate>
</item>
```

### Steps to reproduce
1. launch itau ri app
2. click to open item.media of Relatórios / Pilar 3 e Índice de ISG / Anexo I e II - Pilar 3 - 1T19

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
Response headers of media url 

```
HTTP/1.0 200 OK => 
Content-Length => 895840
Content-Type => application/xlsx
Server => Microsoft-IIS/8.5
p3p => CP="IDC DSP COR ADM DEVi TATi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
Content-Disposition => inline; filename="Anexos I e II - Pilar 3 - 1T19.xlsx"
Content-Security-Policy => default-src https: data: 'unsafe-inline' 'unsafe-eval'
...
```

On mongodb the item.media saved is

```json
{
"_id" : ObjectId("5c58b5fa41ef16f9538b4569"),
"medias" : [
{
"url" : "https://www.itau.com.br/relacoes-com-investidores/Download.aspx?Arquivo=wroEQOBVg4/KSJsiOecPUg==",
"type" : "application/xlsx",
"title" : "Anexo I e II - Pilar 3 - 4T18",
"length" : NumberLong(843596),
"thumbnails" : [ ],
"extension" : null
}
]
},
```

Tried on Android and it also raised an error.

## Try to open same item.media from website
On Android 5.1 download media but can't open it (excel is not installed)
On iOS open media on browser (safari and chrome)

## Why it happens
[ng-meumobi-utils/Files](https://github.com/meumobi/ng-meumobi-utils/blob/master/src/lib/Cordova/Files.js) use [cordova-plugin-file-opener2](https://github.com/pwlin/cordova-plugin-file-opener2) to handle files downloaded.
fileOpener2 ask developer to provide the [mime-type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types), if not try to discover it from file extension.
The correct mime-type for xlsx extension is `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`, but feed provide `application/xlsx`
NB: we could check if mime-type is correct or not by checking if extension is null, if null means that meumobi GenericMediaHandler through [ralouphie/mimey](https://github.com/ralouphie/mimey) can't get extension for given mime and raise an error log.

## how to fix it

## how to test

**Comment by danconte72** [comment]
media type found without extensions 
on it.cse
```js
db.items.distinct("medias.type",{"medias.extension":null})
[
	"application/doc",
	"application/xlsm",
	"application/xlsx",
	"application/docx",
	"text/html",
	"application/",
	"application/pdf",
	"audio/mpeg",
	"application/png",
	"application/xls",
	"application/zip"
]
```
categories with medias.extensions null
```
> db.items.distinct("parent_id",{"medias.extension":null})
[
	NumberLong(640),
	NumberLong(644),
	NumberLong(641),
	NumberLong(632),
	NumberLong(639),
	NumberLong(659),
	NumberLong(656),
	NumberLong(658),
	NumberLong(679),
	NumberLong(680),
	NumberLong(651),
	NumberLong(654),
	NumberLong(629),
	NumberLong(642),
	NumberLong(707),
	NumberLong(708),
	NumberLong(648),
	NumberLong(653),
	488,
	NumberLong(630),
	NumberLong(643),
	NumberLong(636),
	NumberLong(661)
]
```

**Comment by danconte72** [comment]
script tested
> ```sql
> $ update categories set modified = now() where id=651;
> ```
```SQL
mysql> select modified from categories where id=16;
+---------------------+
| modified            |
+---------------------+
| 2019-05-27 17:37:01 |
+---------------------+
1 row in set (0.00 sec)

mysql> update categories set modified = now() where id=16;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select modified from categories where id=16;
+---------------------+
| modified            |
+---------------------+
| 2019-06-13 18:55:43 |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by vdias38** [comment]
I've created a new issue to monitor process remote media #670
