### ISSUE TITLE
Feeds are out-to-date

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#34]
# What Occurs
Articles on home of triunfopt.int-meumobilesite.com are outdated.
A new one is avalaible on site-builder but not appears when I open the site on my browser.
If I open the page of the category it appears and when go back to home is displayed.

# How to reproduce
Add new item in any feed displayed on home and open the site (IRmobi theme). Datas should not been updated.

**Comment by t4deu** [comment]
This could be related to #14, I will check
