### ISSUE TITLE
results badly displayed when feed contains annual reports

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#356]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![IR_Embraer](https://user-images.githubusercontent.com/9011612/70587806-d470f780-1bc2-11ea-8408-0050414ed37a.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
on results.js seems to be mandatory to have a 4-digit title, when it's 'ANNUAL' then it breaks

```
function getYearFromResultsTitle(title) {
        return 20+title.substring(2, 4);
      }
```

**Comment by vdias38** [comment]
Was not included as requirement when feature was developed on #321 
On website annual item follow quarterly results, ex. 1T19, 2T19, 3T19, 4T19, ANNUAL

**Comment by danconte72** [comment]
To fit with 5 tabs we can show like

1T, 2T, 3T, 4T, Annual

**Comment by danconte72** [comment]
[Results Feed](https://ri.embraer.com.br/FeedMeuMobi.aspx?idCanal=dwxMd7dcHTw/kwbNAc2ESQ==)
- annual items has not year on title
- feed is top-down processed,
- set annual item.year as latest processed - 1
