### ISSUE TITLE
Events are unordered: tested on Raia Project 

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#59]
seems ok on api response but appears unordered on App
When I reload the page it aleatory appears ordered or not

**Comment by elbidone** [comment]
I think there's an issue concerning the use of httpwithfallback with query string
items appears firstly unordered like 
http://mobi.comunique-se.com.br/api/raiadrogasilpt.int-meumobilesite.com/categories/481/items
And promise resolve the correct url
http://mobi.comunique-se.com.br/api/raiadrogasilpt.int-meumobilesite.com/categories/481/items?order=start_date,DESC&page=1

**Comment by elbidone** [comment]
When App do `http://mobi.comunique-se.com.br/api/santanderpt.mobi.comunique-se.com.br/categories/92/items?order=start_date,DESC&page=1` Request it saves `http://mobi.comunique-se.com.br/api/santanderpt.mobi.comunique-se.com.br/categories/92/items`

But when it does `Request URL:http://mobi.comunique-se.com.br/api/santanderpt.mobi.comunique-se.com.br/categories/92/items?category=92&limit=20&page=2` it saves `http://mobi.comunique-se.com.br/api/santanderpt.mobi.comunique-se.com.br/categories/92/items?category=92&limit=20&page=2`

Then it seems that httpwithfallback has an issue with '_' or comma separated values 'start_date,DESC'
