### ISSUE TITLE
Use gulp for App building

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#6]

**Comment by elbidone** [comment]
Inspired by gulpfile.js of infoMobi project, I recommend to follow the sequence below:
- Import js libraries from bower. To achieve it you'll need to create irmobi-gulp/src and irmobi-gulp/www, and save irmobi-gulp/gulpfile.js

**Comment by t4deu** [comment]
The first part of the build is complete, the available libraries now are imported with bower, the bootstrap, angularjs are updated and the css and javascripts are being compressed on single files.

But the the previous listed questions remain and the build must be tested on apps

**Comment by t4deu** [comment]
There is a Wope error on the web app, probally because the jquery lib is parsed by Wope:
http://santander.int-meumobi.com/themes/rimobi/js/app.min.js

**Comment by t4deu** [comment]
The Wope error has fixed by including the minified(jquery.mim.js) version, it has less code comments than the raw version.

**Comment by t4deu** [comment]
Now following the Infobox implementation:
* Create a "projects" folder to store the settings, assets and release certificates of each project
* Create the "phonegap-config" and "app-assets" tasks to generate the app config.xml and set the app icons and splash images
* Update the "js" task to generate the "settings.js" with the settings that currently are stored in the "index.html"
* Create the "release" task, that will build the app based on the project that is passed by parameter

**Comment by t4deu** [comment]
The settings required on each projects/{project}/config.json are:
* version
* name
* id
* description
* domains
* sitebuilder
* analytics
* pushwoosh

For projects that require custom layouts changes, update the "partials" task to subscribe partials if the same partial file is present in the projects folder, this is more simple and allow greater customization than using a template system to customize the layout.


For example if the contact page need be customized.
Copy:
```
theme/
  partials/
    contact.html
``` 
to:
```
projects/
  {project}/
    theme/
      partials/
        contact.html
```
and make the required changes

**Comment by t4deu** [comment]
The required changes are:
Update gulpfile.js tasks:
* app-assets - copy the app assets(res) and generate the defaults icon and splash images
* webputty - download the custom css if necessary
* js - besides concat and compress the scripts, it will parse the params of the project "config.json" in the "/js/app/settings.js"
* html - copy the partials and apply the layout customization of the project by replacing the default partials for any partial in the project folder
* phonegap-config - generate the app config.xml
* zip - create a compressed file of the generated "www" folder
* release - generate and compress a app release using the previous tasks

Settings per project:
**Cielo:**
```
projects/
 cielo/
   res/
     icon/
     screen/
   push/
   build.phonegap/
   config.json
```
config.json
```json
{
  "version": "1.1.0",
  "name": "Cielo IR",
  "id": "com.riweb.cielo",
  "description": "Cielo Relações com Investidores",
  "domains": {
   "pt": "cielopt.int-meumobilesite.com",
   "en": "cieloen.int-meumobilesite.com"
  },
  "sitebuilder_url": "http://mobi.comunique-se.com.br",
  "webputty_url": "http://meu-css-manager.appspot.com/css/ahFzfm1ldS1jc3MtbWFuYWdlcnIMCxIEUGFnZRjRqSEM",
  "analytics": "UA-22519238-11",
  "pushwoosh": {
    "applicationCode": "E2137-A18C0",
		"googleProjectNumber": "301191303545"
  }
}
```

**Triunfo**
.....

**Comment by elbidone** [comment]
dixit Tadeu 
> What update are needed on scripts, templates and config.xml to migrate project on gulp

dixit Victor
> I'll update the project IRmobi to use a single repo for all Apps. I need the path of files to update and what to update.

**Comment by t4deu** [comment]
Create the src/js/settings.js:
```javascript
var config_data = {
  DOMAINS: @@DOMAINS,
  SITEBUILDER: @@SITEBUILDER,
  PUSHWOOSH: @@PUSHWOOSH,
  ANALYTICS: @@ANALYTICS,
  IS_APP: true
 }
```
 Update the "js" task in "src/gulpfile.js" to parse and inject the src/js/settings.js before app scripts:
```
 gulp.task('js', function() {
  ...
  gulp.src(config.vendor.js),
  //PARSE AND INJECT HERE
  gulp.src('./src/js/app/**/*.js').pipe(ngFilesort()),
  ...
 });
```
Update the src/tpl/index/index.tpl to remove the template-engine dependency:
 Remove settings if is a build request:
```
  {if !$build}
    var config_data = {DOMAINS: {}};                                                                                                                                                                   |~                                       
    {/literal}                                                                                                                                                                                         |~                                       
    config_data.DOMAINS.{$current_locale} = "{$domain}";                                                                                                                                               |~                                       
    config_data.SITEBUILDER = "{$smarty.const.SITE_BUILDER_URL}"; //REMOVE IF SANTANDER                                                                                                                |~                                       
    config_data.HOME = "{$performance.site.theme.layout_alternatives.home}";                                                                                                                           |~                                       
    config_data.IS_APP = {if $build}true{else}false{/if};                                                                                                                                              |~                                       
    {if $build}                                                                                                                                                                                        |~                                       
    config_data.PUSH = {literal}{appId: "482BE-4B9BA", gcmProjectNumber: "706933317564"};{/literal}                                                                                                    |~                                       
    {/if}                                                                                                                                                                                              |~                                       
    config_data.ANALYTICS = '{if is_array($performance.site.analytics_token)}{$performance.site.analytics_token[1]}{else}{$performance.site.analytics_token}{/if}';  
  {/endif}
```
Replace the title in src/tpl/index/index.tpl:
```html
<title>{if $build}@@TITLE{else}{$performance.site.title}{/if}</title>
```
Remove the navbar from the src/tpl/index/index.tpl, move to a partial in src/partials/layout/_navbar.html:
```html
  <!-- nav -->
  <nav id="nav" class="nav-primary hidden-xs {{performance.site.theme.layout_alternatives.nav}}">
    <ul class="nav" data-spy="affix" data-offset-top="50" nav-menu="active">
      <li>
      </li>
      <li id="home" ng-class="{ active: isActive('/')}">
        <a ng-click="goTo('/')">
          <i class="fa fa-home fa-lg"></i><span translate>Home</span>
        </a>
      </li>
      <li ng-repeat="category in performance.categories"
        id="nav-category-{{category.id}}"
        class="dropdown-submenu" ng-class="{ active: isActive('/category/'+category.id)}">
        <a ng-if="!category.children.length" ng-click="goTo('/'+category.type+'/'+category.id)">
          <i class="fa fa-chevron-circle-right fa-lg"></i><span ng-bind="category.title"></span>
        </a>
        <a ng-if="category.children.length">
          <i class="fa fa-chevron-circle-right fa-lg"></i><span ng-bind="category.title"></span>
        </a>
        <ul class="dropdown-menu" ng-if="category.children.length">
          <li ng-repeat="subCategory in category.children">
            <a ng-click="goTo('/'+subCategory.type+'/'+subCategory.id)" ng-bind="subCategory.title"></a>
          </li>
        </ul>
      </li>
      
            <li id="files" ng-class="{ active: isActive('/files')}">
        <a ng-click="goTo('/files')">
          <i class="fa fa-files-o fa-lg"></i><span ng-bind="'Files'|translate"></span>
        </a>
      </li>
            
     <li id="news" ng-if="performance.news.length" ng-class="{ active: isActive('/news')}">
        <a ng-click="goTo('/news')">
          <i class="fa fa-rss fa-lg"></i><span ng-bind="performance.newsCategory.title"></span>
        </a>
      </li>
     <li id="contact" ng-class="{ active: isActive('/contact')}">
        <a ng-click="goTo('/contact')">
          <i class="fa fa-envelope-o fa-lg"></i><span ng-bind="performance.site.theme.tokens.contact|translate"></span>
        </a>
      </li>
    </ul>
  </nav>
  <!-- / nav -->
```
  in the src/tpl/index/index.tpl:
  <ng-include src="partials/layout/_navbar.html" />
 
 Need to download the index.html from the app site:
 > GET {site_domain}/?build=true

...

**Comment by elbidone** [comment]
?? it's not possible that only these files are necessary to update. 
where are contact of santander, link to triunfo form, remove pagination of triunfo, remove old events of triunfo, config.xml, etc. ?

I don't understand why I need to move navbar to a partial for the gulpification ?

This issues is about gulpification, **I NEED THE LIST OF FILES AND SNIPPETS THAT DIFFER FOR PROJECTS** TO TURN THEM DYNAMIC. YOU CAN CONSIDER WEBAPP AS A PROJECT LIKE TRIUNFO APP BECAUSE BY GULP I WILL RAISE THE CORRECT CODE FOR WEBAPP, NO NEED OF "if $build". BUT TO ACHIEVE IT I NEED THE LIST OF FILES AND SNIPPETS. 

**I don't need comments about your refactoring introducing settings.js, partials or anything else**

**Comment by t4deu** [comment]
**Analytics track Id:**
file: index.html
130: config_data.ANALYTICS = 'UA-22519238-10'; //hardcoded, also available in /performance request

**Comment by elbidone** [comment]
- Why you use **com.adobe.plugins.gaplugin AND angulartics** ? Seems to be redundant
- on gulpfile.js sometimes you **import the min.js** of lib sometimes non-minified file. jquery.js vs jquery.min.js, bootstrap.js vs bootstrap.min.js,... etc.  It's inconsitent! The correct way is to use only minified files.
- I think we can **remove angular-file-upload-shim**, only needed for non-html5 browsers
- **ng-file-upload could be installed through bower**: https://github.com/danialfarid/ng-file-upload-shim-bower
- **angular-local-storage could be installed through bower**: https://github.com/grevory/angular-local-storage
- **I don't find where we use angular-local-storage**
- **I don't find where we use angular-slugify**
- **AVOID using libs from src directory MUST use dist/**. For example AVOID ./bower_components/angulartics/src/angulartics.js USE ./bower_components/angulartics/dist/angulartics.min.js
- What's the use of `<feature name="http://api.phonegap.com/1.0/device"/>` on config.xml ?
- What's the meaning of following lines on config.xml ? Should not be redundant ?
```
<access origin="*"/>
<access origin="*.pushwoosh.com"/>
```
- I don't understand what is Triunfo specific on your comment "Triunfo hide old events".  Setting a class future-events is site agnostic, and if a site want to hide past events could achieve it by css.
- I don't understand what is the purpose of "Triunfo hide pagination", ng-if show pagination if totalpages > , how do it hides ?

**Comment by elbidone** [comment]
After a call meeting with @tadeu
- angulartics is for webapp and plugin for app
- slugify maybe was used to generate urls of images but seems to be obsolet
- angular-local-storage maybe was removed
- don't know the use of feature tag on config.xml
- Triunfo hide old events" is not relevant
- "Triunfo hide pagination" is not relevant

**Comment by elbidone** [comment]
I've finished the gulpification of generic App. Need to add specific behavior: Triunfo, Santander.
And deploy the web version

**Comment by elbidone** [comment]
I've created new issues #72 and #73 about resp. Triunfo and Santander
