### ISSUE TITLE
Remove translations from index.html, use yaml files

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#84]
https://scotch.io/tutorials/internationalization-of-angularjs-applications

**Comment by vdias38** [comment]
Check [nfmb-v2](https://github.com/meumobi/infomobi-v2/commit/6a5310ed59df0e4199ef4b0240f951362d349994#diff-da76a24e770819acc07c09ce0201678b) implementation of [angular-translate](https://angular-translate.github.io/).

Warning nfmb-v2 use v2.7, latest is v2.18

**Comment by danconte72** [comment]
there is a translation implemented on irmobi based on https://codecondo.com/learn-an-easy-way-to-create-a-multilingual-angularjs-app/

should keep solution but update to
- extract translations of [index.html](https://github.com/meumobi/IRmobi/blob/96596199c4f1d2b99b556a9692f1683f634a1146/src/html/index.html#L163) and set on src/locales/en.js and pt.js following the structure
```js
(function(){ var myApp = angular.module("myApp"); myApp.labels_sq = { "version": "Verzioni", "name": "Emri", "surname": "Mbiemri" }; }());
```
- on [app.js](https://github.com/meumobi/IRmobi/blob/master/src/js/app/app.js#L165) update loader to load translate from files 
```
$translateProvider.translations("sq", myApp.labels_sq);
```
- translate pipe is already set on irmobi
